FROM fabienors/almalinux-8-swigex0-r

# UPDATE repo
RUN dnf -y update

# INSTALL dependencies
RUN dnf -y install gdal-devel proj-devel geos-devel sqlite-devel udunits2-devel

# INSTALL R dependencies
RUN Rscript -e "install.packages (c('ggpubr', 'ggplot2', 'ggnewscale'), repos='https://cloud.r-project.org/', dependencies = TRUE)"
        
# Install recent Boost HEADER header files
# ==============================================================
RUN wget https://archives.boost.io/release/1.88.0/source/boost_1_88_0.tar.gz && \
    tar -xvzf boost_1_88_0.tar.gz && \
    cd boost_1_88_0 && \
    ./bootstrap.sh --prefix=/usr/local --with-libraries=all && \
    ./b2 install -j$(nproc) && \
    cd .. && \
    rm -rf boost_1_88_0*
        
# Install recent nlopt header files
# ==============================================================
RUN wget https://github.com/stevengj/nlopt/archive/v2.10.0.tar.gz && \
    tar -xvzf v2.10.0.tar.gz && \
    cd nlopt-2.10.0 && \
    mkdir build && cd build && \
    cmake -DBUILD_SHARED_LIBS=OFF -DNLOPT_GUILE=OFF -DNLOPT_MATLAB=OFF -DNLOPT_OCTAVE=OFF -DNLOPT_PYTHON=OFF -DNLOPT_SWIG=OFF -DNLOPT_TESTS=OFF .. && \
    cmake --build . --parallel 3 && \
    cmake --build . --target install

# Install recent Eigen3 header files
# ==============================================================
RUN wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && \
    tar -xvzf eigen-3.4.0.tar.gz && \
    cd eigen-3.4.0 && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make install && \
    cd ../.. && \
    rm -rf eigen-3.4.0*

# Install recent HDF5 lib
# ==============================================================
RUN wget https://github.com/HDFGroup/hdf5/releases/download/hdf5_1.14.6/hdf5-1.14.6.tar.gz && \
    tar -xvzf hdf5-1.14.6.tar.gz && \
    cd hdf5-1.14.6 && \
    mkdir build && cd build && \
    cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DHDF5_BUILD_EXAMPLES=OFF -DHDF5_BUILD_HL_LIB=OFF -DHDF5_BUILD_CPP_LIB=ON -DHDF_PACKAGE_NAMESPACE=hdf5:: -DHDF5_INSTALL_MOD_FORTRAN=NO -DHDF5_BUILD_GENERATORS=ON -DHDF5_ENABLE_ALL_WARNINGS=ON -DHDF5_MINGW_STATIC_GCC_LIBS=ON -DHDF5_ALLOW_EXTERNAL_SUPPORT=TGZ -DTGZPATH=../temp -DZLIB_PACKAGE_NAME=zlib -DZLIB_TGZ_ORIGPATH=https://github.com/madler/zlib/releases/download/v1.3.1 -DZLIB_TGZ_NAME=zlib-1.3.1.tar.gz -DLIBAEC_PACKAGE_NAME=libaec -DLIBAEC_TGZ_ORIGPATH=https://github.com/MathisRosenhauer/libaec/releases/download/v1.1.3 -DLIBAEC_TGZ_NAME=libaec-1.1.3.tar.gz -DHDF5_PACKAGE_EXTLIBS=ON -DHDF5_USE_ZLIB_NG=OFF -DZLIB_USE_LOCALCONTENT=OFF -DLIBAEC_USE_LOCALCONTENT=OFF -DHDF5_USE_ZLIB_STATIC=ON -DHDF5_USE_LIBAEC_STATIC=ON .. && \
    cmake --build . --parallel 3 && \
    cmake --build . --target install

