FROM fabienors/ubuntu-16-swigex0

# Install dev libs & tools (for gstlearn)
# ==============================================================
RUN apt-get install -y libboost-dev &&\
    apt-get install -y libeigen3-dev

# Install HDF5 lib (for gstlearn)
# ==============================================================
RUN wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.1/src/CMake-hdf5-1.12.1.tar.gz &&\
    tar -xvf CMake-hdf5-1.12.1.tar.gz &&\
    cd CMake-hdf5-1.12.1 &&\
    mkdir build &&\
    cd build &&\
    cmake -DHDF5_GENERATE_HEADERS:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=OFF -DDEFAULT_API_VERSION:STRING=v110 -DCMAKE_BUILD_TYPE:STRING=Release -DHDF5_BUILD_FORTRAN:BOOL=OFF -DHDF5_BUILD_CPP_LIB:BOOL=ON -DHDF5_BUILD_JAVA:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/opt/hdf5-1.12.1 -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DHDF5_BUILD_TOOLS:BOOL=OFF ../hdf5-1.12.1 &&\
    make -j 8 &&\
    make install &&\
    cd ../.. &&\
    rm -rf CMake-hdf5-1.12.1*



