name: manylinux_2_28 for gstlearn-based R software

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push manylinux_2_28-swigex0-r docker
        working-directory: .
        run: |
          docker build -t ${{env.USER}}/manylinux_2_28-gstlearn-r -f manylinux/2_28/Dockerfile_gstlearn_r .
          docker login -u ${{env.USER}} -p ${{env.TOKEN}}
          docker push ${{env.USER}}/manylinux_2_28-gstlearn-r
          docker logout
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
